name: Flutter Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [android, ios, linux, windows]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.2'
          channel: 'stable'

      - run: flutter pub get

      - run: |
          if [ "${{ matrix.platform }}" == "android" ]; then
            flutter build apk --release
            mkdir -p release && cp build/app/outputs/flutter-apk/app-release.apk release/
          elif [ "${{ matrix.platform }}" == "ios" ]; then
            flutter build ios --release --no-codesign
            mkdir -p release && cp -r build/ios/iphoneos release/
          elif [ "${{ matrix.platform }}" == "linux" ]; then
            sudo apt-get update
            sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
            flutter config --enable-linux-desktop
            flutter build linux --release
            mkdir -p release && cp -r build/linux/x64/release/bundle release/
          elif [ "${{ matrix.platform }}" == "windows" ]; then
            flutter config --enable-windows-desktop
            flutter build windows --release
            mkdir -p release && cp -r build/windows/runner/Release release/
          fi

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-release
          path: release/

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: release/

      - run: |
          VERSION=$(date +'%Y.%m.%d-%H%M')
          echo "Creating release version $VERSION"

      - uses: softprops/action-gh-release@v1
        with:
          files: release/*
          tag_name: ${{ github.run_number }}
          release_name: "Release ${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
