name: Flutter Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Java 17
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Install Android SDK dependencies
      - name: Install Android SDK Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            unzip \
            openjdk-17-jdk \
            lib32z1 \
            lib32ncurses6 \
            lib32stdc++6 \
            lib32gcc-s1

          

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.2'
          channel: 'stable'

      # Install Flutter dependencies
      - run: flutter pub get

      # Clean and build APK
      - run: flutter clean
      - run: flutter build apk --release

      # Upload the APK artifact
      - uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk

  create-release:
    needs: [build-and-release-android]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: release/

      - run: |
          VERSION=$(date +'%Y.%m.%d-%H%M')
          echo "Creating release version $VERSION"

      - uses: softprops/action-gh-release@v1
        with:
          files: release/*
          tag_name: ${{ github.run_number }}
          release_name: "Release ${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
