name: Flutter Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Java 17 for Android build
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.2'
          channel: 'stable'

      # Install dependencies and build Android APK
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --release

      # Upload the APK artifact
      - uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk

  build-and-release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Flutter for Windows
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.2'
          channel: 'stable'

      # Install dependencies and build Windows EXE
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build windows --release

      # Upload the Windows artifact
      - uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: build/windows/runner/Release/*.exe

  create-release:
    needs: [build-and-release-android, build-and-release-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: android-release

      - uses: actions/download-artifact@v3
        with:
          name: windows-release

      - uses: ncipollo/release-action@v1
        with:
          artifacts: |
            android-release/app-release.apk
            windows-release/*.exe
          token: ${{ secrets.GITHUB_TOKEN }}

